services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gameops-sqlserver
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: GameOps_123!Strong
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - gameops-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gameops-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__DefaultConnection: >
        Server=sqlserver;
        Database=GameOpsDB;
        User Id=sa;
        Password=GameOps_123!Strong;
        TrustServerCertificate=True;
        Encrypt=False;
    ports:
    - "5000:80"
    networks:
      - gameops-network
    depends_on:
      - sqlserver

  blazor:
    build:
      context: .
      dockerfile: GameOps.Blazor/Dockerfile
    container_name: gameops-blazor
    ports:
      - "7049:80"
    depends_on:
      - api
    networks:
      - gameops-network

networks:
  gameops-network:
    driver: bridge

volumes:
  sqlserver-data:
